<a href="https://colab.research.google.com/github/Ammu3103/Matplotlib-Numpy-Pandas-Seaborn-Notes/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to numpy


**Benefits of numpy array over a list**

> Less Memory

> Fast

> Convinient

















In [ ]:
import numpy as np
import time
import sys

In [ ]:
a=np.array([1,2,3])#1D Array
b=np.array([2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a.dot(b))
a[0]

[3 5 7]
[-1 -1 -1]
[ 2  6 12]
[0.5        0.66666667 0.75      ]
20


1

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])#2d---array
print(a.ndim)
print(a.itemsize)

2
8


In [ ]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)#2d---array,dtype=complex
print(a.ndim)
print(a.dtype)
print(a)
print(a.size)#number of elements in array
print(a.shape)#matrix representation of array
print(a.itemsize)

2
float64
[[1. 2.]
 [3. 4.]
 [5. 6.]]
6
(3, 2)
8


In [ ]:
np.zeros((3,5))#Generates (3,5)shaped 0 array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,5))#Generates (3,5)shaped 1 array

In [ ]:
l=range(5)
print(l)
print(l[0])

range(0, 5)
0


In [ ]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
a=np.arange(1,9,3)#np.arange(start,end,step)
a

array([1, 4, 7])

In [ ]:
a=np.linspace(1,5,10)#np.linspace(start,end,num) here means linearly spaced

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.ravel())
print(a.reshape(2,3))
print(a.max())
print(a.min())
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(np.sqrt(a))
print(np.std(a))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
6
1
21
[ 9 12]
[ 3  7 11]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
1.707825127659933


# Slicing,Indexing Array


In [ ]:
a=np.array([6,7,8])
b= np.array([[6,7,8],[9,0,4],[1,2,3]])
print(a[0:2])
print(a[-1])
print(b[0:2,2])
print(b[-1])
print(b[-1,0:2])
print(b[:,1:])


[6 7]
8
[8 4]
[1 2 3]
[1 2]
[[7 8]
 [0 4]
 [2 3]]


In [ ]:
a= np.array([[6,7,8],[9,0,4],[1,2,3]])
for row in a:
  print(row)
for cell in a.flat:
  print(cell)

[6 7 8]
[9 0 4]
[1 2 3]
6
7
8
9
0
4
1
2
3


In [ ]:
from numpy.core.shape_base import vstack
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a)
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [ ]:
a=np.arange(30).reshape(2,15)
res= np.hsplit(a,3)
resv=np.vsplit(a,2)
print(res[0])
print(res[1])
print(res[1])
print('---------------')
print(resv[0])
print(resv[1])

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
---------------
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [ ]:
a=np.arange(12).reshape(3,4)
b=a>4
print(a)
print(b)
print(a[b])
print(a[b]==-1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[False False False False False False False]


# Iterate numpy array using nditer


In [ ]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for row in a:
  for cell in row:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for cell in a.flatten():
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for x in np.nditer(a,order='c'):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for x in np.nditer(a,order='F'):
  print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [ ]:
for x in np.nditer(a,order='F',flags=['external_loop']):
  print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [ ]:
for x in np.nditer(a,order='F',op_flags=['readwrite']):
  x[...]=x*x

In [ ]:
a


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
b = np.arange(3,15,4).reshape(3,1 )
b

array([[ 3],
       [ 7],
       [11]])

In [ ]:
for x,y in np.nditer([a,b]):#in this shape both arrays shape should be competable
  print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
